{"uid":"1c9ffbe6d0a3fa4e","name":"Проверка создания пользователя","fullName":"tests.test_ui.test_first#test_positive_registration_with_fixture_params","historyId":"cf18eed7ed2621160679c51f2fcec754","time":{"start":1760786808056,"stop":1760786811142,"duration":3086},"description":"\nЭтот тест проверяет:\n- Регистрацию пользователя с позитивным сценарием\n- Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n- Проверка успеха прохождения регистрации \nИЛИ\n- Проверка предупреждения, что пользователь уже создан с таким email\n","descriptionHtml":"<p>Этот тест проверяет:</p>\n<ul>\n<li>Регистрацию пользователя с позитивным сценарием</li>\n<li>Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)</li>\n<li>Проверка успеха прохождения регистрации<br />\nИЛИ</li>\n<li>Проверка предупреждения, что пользователь уже создан с таким email</li>\n</ul>\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x55aa8406c67a <unknown>\n#1 0x55aa83aeb566 <unknown>\n#2 0x55aa83ae2470 <unknown>\n#3 0x55aa83ad3926 <unknown>\n#4 0x55aa83ad572b <unknown>\n#5 0x55aa83ad3eb1 <unknown>\n#6 0x55aa83ad3650 <unknown>\n#7 0x55aa83ad3302 <unknown>\n#8 0x55aa83ad1142 <unknown>\n#9 0x55aa83ad192a <unknown>\n#10 0x55aa83aeea99 <unknown>\n#11 0x55aa83b89ee5 <unknown>\n#12 0x55aa83b63632 <unknown>\n#13 0x55aa83b89328 <unknown>\n#14 0x55aa83b63403 <unknown>\n#15 0x55aa83b2fb02 <unknown>\n#16 0x55aa83b307c1 <unknown>\n#17 0x55aa84030448 <unknown>\n#18 0x55aa840342af <unknown>\n#19 0x55aa840178d9 <unknown>\n#20 0x55aa84034e55 <unknown>\n#21 0x55aa83ffd13f <unknown>\n#22 0x55aa840594b8 <unknown>\n#23 0x55aa84059693 <unknown>\n#24 0x55aa8406b613 <unknown>\n#25 0x7fb7ef2bab7b <unknown>","statusTrace":"browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6bf004c5ceb860c9fc076c27a21906c1\")>\nbase_url = 'http://31.59.174.108'\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"6bf004c5ceb860c9fc076c27a21906c1\")>\nregistration_data_with_params = {'email': 'test3@mail.ru', 'name': 'User26', 'password': 'qwertyu2'}\n\n    @allure.epic(\"Аутентификация и авторизация\")\n    @allure.feature(\"Регистрация пользователей\")\n    @allure.suite(\"Смоук тесты\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.tag(\"smoke\", \"ui\")\n    @allure.label(\"owner\", \"QA - evgeny_gord\")\n    @allure.id(\"TEST-123\")\n    @allure.title(\"Проверка создания пользователя\")\n    @allure.description(\"\"\"\n    Этот тест проверяет:\n    - Регистрацию пользователя с позитивным сценарием\n    - Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n    - Проверка успеха прохождения регистрации\n    ИЛИ\n    - Проверка предупреждения, что пользователь уже создан с таким email\n    \"\"\")\n    @allure.link(\"https://jira.example.com/TEST-123\", name=\"JIRA Task\")\n    @allure.issue(\"BUG-456\", \"https://bugtracker.com/BUG-456\")\n    @allure.testcase(\"TC-789\", \"https://testcase.com/TC-789\")\n    def test_positive_registration_with_fixture_params(browser, base_url, wait, registration_data_with_params):\n        #driver = webdriver.Chrome(service=Service(executable_path='C:/chromedriver.exe'))\n        # driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n        # driver.get(url)\n        with allure.step('Переход на страницу Регистрации'):\n>           browser.get(f\"{base_url}/sign_up\")\n\ntests/test_ui/test_first.py:183: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f66f536bad0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55aa84059693 \\\\u003Cunknown>\\\\n#24 0x55aa8406b613 \\\\u003Cunknown>\\\\n#25 0x7fb7ef2bab7b \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\") if isinstance(message, dict) else None\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=141.0.7390.107)\nE       Stacktrace:\nE       #0 0x55aa8406c67a <unknown>\nE       #1 0x55aa83aeb566 <unknown>\nE       #2 0x55aa83ae2470 <unknown>\nE       #3 0x55aa83ad3926 <unknown>\nE       #4 0x55aa83ad572b <unknown>\nE       #5 0x55aa83ad3eb1 <unknown>\nE       #6 0x55aa83ad3650 <unknown>\nE       #7 0x55aa83ad3302 <unknown>\nE       #8 0x55aa83ad1142 <unknown>\nE       #9 0x55aa83ad192a <unknown>\nE       #10 0x55aa83aeea99 <unknown>\nE       #11 0x55aa83b89ee5 <unknown>\nE       #12 0x55aa83b63632 <unknown>\nE       #13 0x55aa83b89328 <unknown>\nE       #14 0x55aa83b63403 <unknown>\nE       #15 0x55aa83b2fb02 <unknown>\nE       #16 0x55aa83b307c1 <unknown>\nE       #17 0x55aa84030448 <unknown>\nE       #18 0x55aa840342af <unknown>\nE       #19 0x55aa840178d9 <unknown>\nE       #20 0x55aa84034e55 <unknown>\nE       #21 0x55aa83ffd13f <unknown>\nE       #22 0x55aa840594b8 <unknown>\nE       #23 0x55aa84059693 <unknown>\nE       #24 0x55aa8406b613 <unknown>\nE       #25 0x7fb7ef2bab7b <unknown>\n\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":8,"retriesStatusChange":true,"beforeStages":[{"name":"_session_faker","time":{"start":1760786703904,"stop":1760786704085,"duration":181},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"browser","time":{"start":1760786796115,"stop":1760786808051,"duration":11936},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1760786808051,"stop":1760786808051,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"registration_data_with_params","time":{"start":1760786808052,"stop":1760786808055,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"wait","time":{"start":1760786808052,"stop":1760786808052,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\nЭтот тест проверяет:\n- Регистрацию пользователя с позитивным сценарием\n- Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n- Проверка успеха прохождения регистрации \nИЛИ\n- Проверка предупреждения, что пользователь уже создан с таким email\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x55aa8406c67a <unknown>\n#1 0x55aa83aeb566 <unknown>\n#2 0x55aa83ae2470 <unknown>\n#3 0x55aa83ad3926 <unknown>\n#4 0x55aa83ad572b <unknown>\n#5 0x55aa83ad3eb1 <unknown>\n#6 0x55aa83ad3650 <unknown>\n#7 0x55aa83ad3302 <unknown>\n#8 0x55aa83ad1142 <unknown>\n#9 0x55aa83ad192a <unknown>\n#10 0x55aa83aeea99 <unknown>\n#11 0x55aa83b89ee5 <unknown>\n#12 0x55aa83b63632 <unknown>\n#13 0x55aa83b89328 <unknown>\n#14 0x55aa83b63403 <unknown>\n#15 0x55aa83b2fb02 <unknown>\n#16 0x55aa83b307c1 <unknown>\n#17 0x55aa84030448 <unknown>\n#18 0x55aa840342af <unknown>\n#19 0x55aa840178d9 <unknown>\n#20 0x55aa84034e55 <unknown>\n#21 0x55aa83ffd13f <unknown>\n#22 0x55aa840594b8 <unknown>\n#23 0x55aa84059693 <unknown>\n#24 0x55aa8406b613 <unknown>\n#25 0x7fb7ef2bab7b <unknown>","statusTrace":"browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6bf004c5ceb860c9fc076c27a21906c1\")>\nbase_url = 'http://31.59.174.108'\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"6bf004c5ceb860c9fc076c27a21906c1\")>\nregistration_data_with_params = {'email': 'test3@mail.ru', 'name': 'User26', 'password': 'qwertyu2'}\n\n    @allure.epic(\"Аутентификация и авторизация\")\n    @allure.feature(\"Регистрация пользователей\")\n    @allure.suite(\"Смоук тесты\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.tag(\"smoke\", \"ui\")\n    @allure.label(\"owner\", \"QA - evgeny_gord\")\n    @allure.id(\"TEST-123\")\n    @allure.title(\"Проверка создания пользователя\")\n    @allure.description(\"\"\"\n    Этот тест проверяет:\n    - Регистрацию пользователя с позитивным сценарием\n    - Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n    - Проверка успеха прохождения регистрации\n    ИЛИ\n    - Проверка предупреждения, что пользователь уже создан с таким email\n    \"\"\")\n    @allure.link(\"https://jira.example.com/TEST-123\", name=\"JIRA Task\")\n    @allure.issue(\"BUG-456\", \"https://bugtracker.com/BUG-456\")\n    @allure.testcase(\"TC-789\", \"https://testcase.com/TC-789\")\n    def test_positive_registration_with_fixture_params(browser, base_url, wait, registration_data_with_params):\n        #driver = webdriver.Chrome(service=Service(executable_path='C:/chromedriver.exe'))\n        # driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n        # driver.get(url)\n        with allure.step('Переход на страницу Регистрации'):\n>           browser.get(f\"{base_url}/sign_up\")\n\ntests/test_ui/test_first.py:183: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f66f536bad0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55aa84059693 \\\\u003Cunknown>\\\\n#24 0x55aa8406b613 \\\\u003Cunknown>\\\\n#25 0x7fb7ef2bab7b \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\") if isinstance(message, dict) else None\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=141.0.7390.107)\nE       Stacktrace:\nE       #0 0x55aa8406c67a <unknown>\nE       #1 0x55aa83aeb566 <unknown>\nE       #2 0x55aa83ae2470 <unknown>\nE       #3 0x55aa83ad3926 <unknown>\nE       #4 0x55aa83ad572b <unknown>\nE       #5 0x55aa83ad3eb1 <unknown>\nE       #6 0x55aa83ad3650 <unknown>\nE       #7 0x55aa83ad3302 <unknown>\nE       #8 0x55aa83ad1142 <unknown>\nE       #9 0x55aa83ad192a <unknown>\nE       #10 0x55aa83aeea99 <unknown>\nE       #11 0x55aa83b89ee5 <unknown>\nE       #12 0x55aa83b63632 <unknown>\nE       #13 0x55aa83b89328 <unknown>\nE       #14 0x55aa83b63403 <unknown>\nE       #15 0x55aa83b2fb02 <unknown>\nE       #16 0x55aa83b307c1 <unknown>\nE       #17 0x55aa84030448 <unknown>\nE       #18 0x55aa840342af <unknown>\nE       #19 0x55aa840178d9 <unknown>\nE       #20 0x55aa84034e55 <unknown>\nE       #21 0x55aa83ffd13f <unknown>\nE       #22 0x55aa840594b8 <unknown>\nE       #23 0x55aa84059693 <unknown>\nE       #24 0x55aa8406b613 <unknown>\nE       #25 0x7fb7ef2bab7b <unknown>\n\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","steps":[{"name":"Переход на страницу Регистрации","time":{"start":1760786808056,"stop":1760786811139,"duration":3083},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x55aa8406c67a <unknown>\n#1 0x55aa83aeb566 <unknown>\n#2 0x55aa83ae2470 <unknown>\n#3 0x55aa83ad3926 <unknown>\n#4 0x55aa83ad572b <unknown>\n#5 0x55aa83ad3eb1 <unknown>\n#6 0x55aa83ad3650 <unknown>\n#7 0x55aa83ad3302 <unknown>\n#8 0x55aa83ad1142 <unknown>\n#9 0x55aa83ad192a <unknown>\n#10 0x55aa83aeea99 <unknown>\n#11 0x55aa83b89ee5 <unknown>\n#12 0x55aa83b63632 <unknown>\n#13 0x55aa83b89328 <unknown>\n#14 0x55aa83b63403 <unknown>\n#15 0x55aa83b2fb02 <unknown>\n#16 0x55aa83b307c1 <unknown>\n#17 0x55aa84030448 <unknown>\n#18 0x55aa840342af <unknown>\n#19 0x55aa840178d9 <unknown>\n#20 0x55aa84034e55 <unknown>\n#21 0x55aa83ffd13f <unknown>\n#22 0x55aa840594b8 <unknown>\n#23 0x55aa84059693 <unknown>\n#24 0x55aa8406b613 <unknown>\n#25 0x7fb7ef2bab7b <unknown>\n\n","statusTrace":"  File \"/app/tests/test_ui/test_first.py\", line 183, in test_positive_registration_with_fixture_params\n    browser.get(f\"{base_url}/sign_up\")\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 483, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"35c11c78d083cfc3","name":"stdout","source":"35c11c78d083cfc3.txt","type":"text/plain","size":137}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"stepsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"browser::0","time":{"start":1760786811238,"stop":1760786811421,"duration":183},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"suite","value":"Смоук тесты"},{"name":"as_id","value":"TEST-123"},{"name":"epic","value":"Аутентификация и авторизация"},{"name":"tag","value":"smoke"},{"name":"feature","value":"Регистрация пользователей"},{"name":"owner","value":"QA - evgeny_gord"},{"name":"severity","value":"critical"},{"name":"tag","value":"ui"},{"name":"parentSuite","value":"tests.test_ui"},{"name":"host","value":"1b79bd22dc0c"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_ui.test_first"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"registration_data_with_params","value":"{'email': 'test3@mail.ru', 'name': 'User26', 'password': 'qwertyu2'}"}],"links":[{"name":"https://testcase.com/TC-789","url":"TC-789","type":"tms"},{"name":"https://bugtracker.com/BUG-456","url":"BUG-456","type":"issue"},{"name":"JIRA Task","url":"https://jira.example.com/TEST-123","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"critical","owner":"QA - evgeny_gord","retries":[{"uid":"85ca1bf9fbf1e847","status":"passed","time":{"start":1760785777365,"stop":1760785785253,"duration":7888}},{"uid":"b5660fc8064bcbfb","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x563d82e7b67a <unknown>\n#1 0x563d828fa566 <unknown>\n#2 0x563d828f1470 <unknown>\n#3 0x563d828e2926 <unknown>\n#4 0x563d828e472b <unknown>\n#5 0x563d828e2eb1 <unknown>\n#6 0x563d828e2650 <unknown>\n#7 0x563d828e2302 <unknown>\n#8 0x563d828e0142 <unknown>\n#9 0x563d828e092a <unknown>\n#10 0x563d828fda99 <unknown>\n#11 0x563d82998ee5 <unknown>\n#12 0x563d82972632 <unknown>\n#13 0x563d82998328 <unknown>\n#14 0x563d82972403 <unknown>\n#15 0x563d8293eb02 <unknown>\n#16 0x563d8293f7c1 <unknown>\n#17 0x563d82e3f448 <unknown>\n#18 0x563d82e432af <unknown>\n#19 0x563d82e268d9 <unknown>\n#20 0x563d82e43e55 <unknown>\n#21 0x563d82e0c13f <unknown>\n#22 0x563d82e684b8 <unknown>\n#23 0x563d82e68693 <unknown>\n#24 0x563d82e7a613 <unknown>\n#25 0x7f0022b7cb7b <unknown>","time":{"start":1760784824416,"stop":1760784827780,"duration":3364}},{"uid":"29c7c669ebb89bb8","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x5630fd27667a <unknown>\n#1 0x5630fccf5566 <unknown>\n#2 0x5630fccec470 <unknown>\n#3 0x5630fccdd926 <unknown>\n#4 0x5630fccdf72b <unknown>\n#5 0x5630fccddeb1 <unknown>\n#6 0x5630fccdd650 <unknown>\n#7 0x5630fccdd302 <unknown>\n#8 0x5630fccdb142 <unknown>\n#9 0x5630fccdb92a <unknown>\n#10 0x5630fccf8a99 <unknown>\n#11 0x5630fcd93ee5 <unknown>\n#12 0x5630fcd6d632 <unknown>\n#13 0x5630fcd93328 <unknown>\n#14 0x5630fcd6d403 <unknown>\n#15 0x5630fcd39b02 <unknown>\n#16 0x5630fcd3a7c1 <unknown>\n#17 0x5630fd23a448 <unknown>\n#18 0x5630fd23e2af <unknown>\n#19 0x5630fd2218d9 <unknown>\n#20 0x5630fd23ee55 <unknown>\n#21 0x5630fd20713f <unknown>\n#22 0x5630fd2634b8 <unknown>\n#23 0x5630fd263693 <unknown>\n#24 0x5630fd275613 <unknown>\n#25 0x7f87ce003b7b <unknown>","time":{"start":1760783569527,"stop":1760783572513,"duration":2986}},{"uid":"85558a1431d70787","status":"passed","time":{"start":1760783220036,"stop":1760783227323,"duration":7287}},{"uid":"2392d57611f0f91c","status":"passed","time":{"start":1760650455678,"stop":1760650466806,"duration":11128}},{"uid":"2a73e853966b22f","status":"passed","time":{"start":1760648930954,"stop":1760648944976,"duration":14022}},{"uid":"4db4260cdc92e5e0","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x558d6e39567a <unknown>\n#1 0x558d6de14566 <unknown>\n#2 0x558d6de4fb4c <unknown>\n#3 0x558d6de4b7c4 <unknown>\n#4 0x558d6de9abd3 <unknown>\n#5 0x558d6de9a286 <unknown>\n#6 0x558d6de8c403 <unknown>\n#7 0x558d6de58b02 <unknown>\n#8 0x558d6de597c1 <unknown>\n#9 0x558d6e359448 <unknown>\n#10 0x558d6e35d2af <unknown>\n#11 0x558d6e3408d9 <unknown>\n#12 0x558d6e35de55 <unknown>\n#13 0x558d6e32613f <unknown>\n#14 0x558d6e3824b8 <unknown>\n#15 0x558d6e382693 <unknown>\n#16 0x558d6e394613 <unknown>\n#17 0x7f1da7b06b7b <unknown>","time":{"start":1760647339738,"stop":1760647339738,"duration":0}},{"uid":"3adbae73322de016","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127","time":{"start":1760646037201,"stop":1760646037201,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["ui","smoke"]},"source":"1c9ffbe6d0a3fa4e.json","parameterValues":["{'email': 'test3@mail.ru', 'name': 'User26', 'password': 'qwertyu2'}"]}