{"uid":"4b932e63abf59bff","name":"Проверка создания пользователя","fullName":"tests.test_ui.test_first#test_positive_registration_with_fixture_params","historyId":"6852ce31fe0093ceef77af096d9d7767","time":{"start":1760785767060,"stop":1760785770273,"duration":3213},"description":"\nЭтот тест проверяет:\n- Регистрацию пользователя с позитивным сценарием\n- Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n- Проверка успеха прохождения регистрации \nИЛИ\n- Проверка предупреждения, что пользователь уже создан с таким email\n","descriptionHtml":"<p>Этот тест проверяет:</p>\n<ul>\n<li>Регистрацию пользователя с позитивным сценарием</li>\n<li>Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)</li>\n<li>Проверка успеха прохождения регистрации<br />\nИЛИ</li>\n<li>Проверка предупреждения, что пользователь уже создан с таким email</li>\n</ul>\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x55593613867a <unknown>\n#1 0x555935bb7566 <unknown>\n#2 0x555935bae470 <unknown>\n#3 0x555935b9f926 <unknown>\n#4 0x555935ba172b <unknown>\n#5 0x555935b9feb1 <unknown>\n#6 0x555935b9f650 <unknown>\n#7 0x555935b9f302 <unknown>\n#8 0x555935b9d142 <unknown>\n#9 0x555935b9d92a <unknown>\n#10 0x555935bbaa99 <unknown>\n#11 0x555935c55ee5 <unknown>\n#12 0x555935c2f632 <unknown>\n#13 0x555935c55328 <unknown>\n#14 0x555935c2f403 <unknown>\n#15 0x555935bfbb02 <unknown>\n#16 0x555935bfc7c1 <unknown>\n#17 0x5559360fc448 <unknown>\n#18 0x5559361002af <unknown>\n#19 0x5559360e38d9 <unknown>\n#20 0x555936100e55 <unknown>\n#21 0x5559360c913f <unknown>\n#22 0x5559361254b8 <unknown>\n#23 0x555936125693 <unknown>\n#24 0x555936137613 <unknown>\n#25 0x7f9b96a24b7b <unknown>","statusTrace":"browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"80cc824f0839d84dfcba610d6855d83d\")>\nbase_url = 'http://31.59.174.108'\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"80cc824f0839d84dfcba610d6855d83d\")>\nregistration_data_with_params = {'email': 'test2@mail.ru', 'name': 'User25', 'password': 'qwertyu1'}\n\n    @allure.epic(\"Аутентификация и авторизация\")\n    @allure.feature(\"Регистрация пользователей\")\n    @allure.suite(\"Смоук тесты\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.tag(\"smoke\", \"ui\")\n    @allure.label(\"owner\", \"QA - evgeny_gord\")\n    @allure.id(\"TEST-123\")\n    @allure.title(\"Проверка создания пользователя\")\n    @allure.description(\"\"\"\n    Этот тест проверяет:\n    - Регистрацию пользователя с позитивным сценарием\n    - Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n    - Проверка успеха прохождения регистрации\n    ИЛИ\n    - Проверка предупреждения, что пользователь уже создан с таким email\n    \"\"\")\n    @allure.link(\"https://jira.example.com/TEST-123\", name=\"JIRA Task\")\n    @allure.issue(\"BUG-456\", \"https://bugtracker.com/BUG-456\")\n    @allure.testcase(\"TC-789\", \"https://testcase.com/TC-789\")\n    def test_positive_registration_with_fixture_params(browser, base_url, wait, registration_data_with_params):\n        #driver = webdriver.Chrome(service=Service(executable_path='C:/chromedriver.exe'))\n        # driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n        # driver.get(url)\n        with allure.step('Переход на страницу Регистрации'):\n>           browser.get(f\"{base_url}/sign_up\")\n\ntests/test_ui/test_first.py:177: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f59f72d1f10>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x555936125693 \\\\u003Cunknown>\\\\n#24 0x555936137613 \\\\u003Cunknown>\\\\n#25 0x7f9b96a24b7b \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\") if isinstance(message, dict) else None\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=141.0.7390.107)\nE       Stacktrace:\nE       #0 0x55593613867a <unknown>\nE       #1 0x555935bb7566 <unknown>\nE       #2 0x555935bae470 <unknown>\nE       #3 0x555935b9f926 <unknown>\nE       #4 0x555935ba172b <unknown>\nE       #5 0x555935b9feb1 <unknown>\nE       #6 0x555935b9f650 <unknown>\nE       #7 0x555935b9f302 <unknown>\nE       #8 0x555935b9d142 <unknown>\nE       #9 0x555935b9d92a <unknown>\nE       #10 0x555935bbaa99 <unknown>\nE       #11 0x555935c55ee5 <unknown>\nE       #12 0x555935c2f632 <unknown>\nE       #13 0x555935c55328 <unknown>\nE       #14 0x555935c2f403 <unknown>\nE       #15 0x555935bfbb02 <unknown>\nE       #16 0x555935bfc7c1 <unknown>\nE       #17 0x5559360fc448 <unknown>\nE       #18 0x5559361002af <unknown>\nE       #19 0x5559360e38d9 <unknown>\nE       #20 0x555936100e55 <unknown>\nE       #21 0x5559360c913f <unknown>\nE       #22 0x5559361254b8 <unknown>\nE       #23 0x555936125693 <unknown>\nE       #24 0x555936137613 <unknown>\nE       #25 0x7f9b96a24b7b <unknown>\n\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":7,"retriesStatusChange":true,"beforeStages":[{"name":"_session_faker","time":{"start":1760785670477,"stop":1760785670646,"duration":169},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentStep":false},{"name":"browser","time":{"start":1760785755311,"stop":1760785767057,"duration":11746},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentStep":false},{"name":"base_url","time":{"start":1760785767057,"stop":1760785767057,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentStep":false},{"name":"registration_data_with_params","time":{"start":1760785767058,"stop":1760785767058,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentStep":false},{"name":"wait","time":{"start":1760785767058,"stop":1760785767058,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentStep":false}],"testStage":{"description":"\nЭтот тест проверяет:\n- Регистрацию пользователя с позитивным сценарием\n- Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n- Проверка успеха прохождения регистрации \nИЛИ\n- Проверка предупреждения, что пользователь уже создан с таким email\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x55593613867a <unknown>\n#1 0x555935bb7566 <unknown>\n#2 0x555935bae470 <unknown>\n#3 0x555935b9f926 <unknown>\n#4 0x555935ba172b <unknown>\n#5 0x555935b9feb1 <unknown>\n#6 0x555935b9f650 <unknown>\n#7 0x555935b9f302 <unknown>\n#8 0x555935b9d142 <unknown>\n#9 0x555935b9d92a <unknown>\n#10 0x555935bbaa99 <unknown>\n#11 0x555935c55ee5 <unknown>\n#12 0x555935c2f632 <unknown>\n#13 0x555935c55328 <unknown>\n#14 0x555935c2f403 <unknown>\n#15 0x555935bfbb02 <unknown>\n#16 0x555935bfc7c1 <unknown>\n#17 0x5559360fc448 <unknown>\n#18 0x5559361002af <unknown>\n#19 0x5559360e38d9 <unknown>\n#20 0x555936100e55 <unknown>\n#21 0x5559360c913f <unknown>\n#22 0x5559361254b8 <unknown>\n#23 0x555936125693 <unknown>\n#24 0x555936137613 <unknown>\n#25 0x7f9b96a24b7b <unknown>","statusTrace":"browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"80cc824f0839d84dfcba610d6855d83d\")>\nbase_url = 'http://31.59.174.108'\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"80cc824f0839d84dfcba610d6855d83d\")>\nregistration_data_with_params = {'email': 'test2@mail.ru', 'name': 'User25', 'password': 'qwertyu1'}\n\n    @allure.epic(\"Аутентификация и авторизация\")\n    @allure.feature(\"Регистрация пользователей\")\n    @allure.suite(\"Смоук тесты\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.tag(\"smoke\", \"ui\")\n    @allure.label(\"owner\", \"QA - evgeny_gord\")\n    @allure.id(\"TEST-123\")\n    @allure.title(\"Проверка создания пользователя\")\n    @allure.description(\"\"\"\n    Этот тест проверяет:\n    - Регистрацию пользователя с позитивным сценарием\n    - Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n    - Проверка успеха прохождения регистрации\n    ИЛИ\n    - Проверка предупреждения, что пользователь уже создан с таким email\n    \"\"\")\n    @allure.link(\"https://jira.example.com/TEST-123\", name=\"JIRA Task\")\n    @allure.issue(\"BUG-456\", \"https://bugtracker.com/BUG-456\")\n    @allure.testcase(\"TC-789\", \"https://testcase.com/TC-789\")\n    def test_positive_registration_with_fixture_params(browser, base_url, wait, registration_data_with_params):\n        #driver = webdriver.Chrome(service=Service(executable_path='C:/chromedriver.exe'))\n        # driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n        # driver.get(url)\n        with allure.step('Переход на страницу Регистрации'):\n>           browser.get(f\"{base_url}/sign_up\")\n\ntests/test_ui/test_first.py:177: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f59f72d1f10>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x555936125693 \\\\u003Cunknown>\\\\n#24 0x555936137613 \\\\u003Cunknown>\\\\n#25 0x7f9b96a24b7b \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\") if isinstance(message, dict) else None\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=141.0.7390.107)\nE       Stacktrace:\nE       #0 0x55593613867a <unknown>\nE       #1 0x555935bb7566 <unknown>\nE       #2 0x555935bae470 <unknown>\nE       #3 0x555935b9f926 <unknown>\nE       #4 0x555935ba172b <unknown>\nE       #5 0x555935b9feb1 <unknown>\nE       #6 0x555935b9f650 <unknown>\nE       #7 0x555935b9f302 <unknown>\nE       #8 0x555935b9d142 <unknown>\nE       #9 0x555935b9d92a <unknown>\nE       #10 0x555935bbaa99 <unknown>\nE       #11 0x555935c55ee5 <unknown>\nE       #12 0x555935c2f632 <unknown>\nE       #13 0x555935c55328 <unknown>\nE       #14 0x555935c2f403 <unknown>\nE       #15 0x555935bfbb02 <unknown>\nE       #16 0x555935bfc7c1 <unknown>\nE       #17 0x5559360fc448 <unknown>\nE       #18 0x5559361002af <unknown>\nE       #19 0x5559360e38d9 <unknown>\nE       #20 0x555936100e55 <unknown>\nE       #21 0x5559360c913f <unknown>\nE       #22 0x5559361254b8 <unknown>\nE       #23 0x555936125693 <unknown>\nE       #24 0x555936137613 <unknown>\nE       #25 0x7f9b96a24b7b <unknown>\n\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","steps":[{"name":"Переход на страницу Регистрации","time":{"start":1760785767060,"stop":1760785770272,"duration":3212},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x55593613867a <unknown>\n#1 0x555935bb7566 <unknown>\n#2 0x555935bae470 <unknown>\n#3 0x555935b9f926 <unknown>\n#4 0x555935ba172b <unknown>\n#5 0x555935b9feb1 <unknown>\n#6 0x555935b9f650 <unknown>\n#7 0x555935b9f302 <unknown>\n#8 0x555935b9d142 <unknown>\n#9 0x555935b9d92a <unknown>\n#10 0x555935bbaa99 <unknown>\n#11 0x555935c55ee5 <unknown>\n#12 0x555935c2f632 <unknown>\n#13 0x555935c55328 <unknown>\n#14 0x555935c2f403 <unknown>\n#15 0x555935bfbb02 <unknown>\n#16 0x555935bfc7c1 <unknown>\n#17 0x5559360fc448 <unknown>\n#18 0x5559361002af <unknown>\n#19 0x5559360e38d9 <unknown>\n#20 0x555936100e55 <unknown>\n#21 0x5559360c913f <unknown>\n#22 0x5559361254b8 <unknown>\n#23 0x555936125693 <unknown>\n#24 0x555936137613 <unknown>\n#25 0x7f9b96a24b7b <unknown>\n\n","statusTrace":"  File \"/app/tests/test_ui/test_first.py\", line 177, in test_positive_registration_with_fixture_params\n    browser.get(f\"{base_url}/sign_up\")\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 483, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true,"stepsCount":0,"attachmentStep":false}],"attachments":[{"uid":"1f8b177170780312","name":"stdout","source":"1f8b177170780312.txt","type":"text/plain","size":137}],"parameters":[],"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true,"stepsCount":1,"attachmentStep":false},"afterStages":[{"name":"browser::0","time":{"start":1760785770364,"stop":1760785770618,"duration":254},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentStep":false}],"labels":[{"name":"tag","value":"smoke"},{"name":"severity","value":"critical"},{"name":"feature","value":"Регистрация пользователей"},{"name":"epic","value":"Аутентификация и авторизация"},{"name":"suite","value":"Смоук тесты"},{"name":"owner","value":"QA - evgeny_gord"},{"name":"as_id","value":"TEST-123"},{"name":"tag","value":"ui"},{"name":"parentSuite","value":"tests.test_ui"},{"name":"host","value":"ecb2b429c773"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_ui.test_first"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"registration_data_with_params","value":"{'email': 'test2@mail.ru', 'name': 'User25', 'password': 'qwertyu1'}"}],"links":[{"name":"https://testcase.com/TC-789","url":"TC-789","type":"tms"},{"name":"https://bugtracker.com/BUG-456","url":"BUG-456","type":"issue"},{"name":"JIRA Task","url":"https://jira.example.com/TEST-123","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"critical","owner":"QA - evgeny_gord","retries":[{"uid":"cc0e167db481b025","status":"passed","time":{"start":1760784805889,"stop":1760784812565,"duration":6676}},{"uid":"ca43482a0a9eda07","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x56307d14a67a <unknown>\n#1 0x56307cbc9566 <unknown>\n#2 0x56307cbc0470 <unknown>\n#3 0x56307cbb1926 <unknown>\n#4 0x56307cbb372b <unknown>\n#5 0x56307cbb1eb1 <unknown>\n#6 0x56307cbb1650 <unknown>\n#7 0x56307cbb1302 <unknown>\n#8 0x56307cbaf142 <unknown>\n#9 0x56307cbaf92a <unknown>\n#10 0x56307cbcca99 <unknown>\n#11 0x56307cc67ee5 <unknown>\n#12 0x56307cc41632 <unknown>\n#13 0x56307cc67328 <unknown>\n#14 0x56307cc41403 <unknown>\n#15 0x56307cc0db02 <unknown>\n#16 0x56307cc0e7c1 <unknown>\n#17 0x56307d10e448 <unknown>\n#18 0x56307d1122af <unknown>\n#19 0x56307d0f58d9 <unknown>\n#20 0x56307d112e55 <unknown>\n#21 0x56307d0db13f <unknown>\n#22 0x56307d1374b8 <unknown>\n#23 0x56307d137693 <unknown>\n#24 0x56307d149613 <unknown>\n#25 0x7fc8ea2f0b7b <unknown>","time":{"start":1760783564948,"stop":1760783567763,"duration":2815}},{"uid":"a983d954dae978a","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55df8a4c967a <unknown>\n#1 0x55df89f48566 <unknown>\n#2 0x55df89f9a68d <unknown>\n#3 0x55df89f9a921 <unknown>\n#4 0x55df89fe8e94 <unknown>\n#5 0x55df89fc065d <unknown>\n#6 0x55df89fe6328 <unknown>\n#7 0x55df89fc0403 <unknown>\n#8 0x55df89f8cb02 <unknown>\n#9 0x55df89f8d7c1 <unknown>\n#10 0x55df8a48d448 <unknown>\n#11 0x55df8a4912af <unknown>\n#12 0x55df8a4748d9 <unknown>\n#13 0x55df8a491e55 <unknown>\n#14 0x55df8a45a13f <unknown>\n#15 0x55df8a4b64b8 <unknown>\n#16 0x55df8a4b6693 <unknown>\n#17 0x55df8a4c8613 <unknown>\n#18 0x7f159029ab7b <unknown>","time":{"start":1760783193579,"stop":1760783207724,"duration":14145}},{"uid":"20b098500867ffc1","status":"passed","time":{"start":1760650443221,"stop":1760650454105,"duration":10884}},{"uid":"ddafa2262edeec68","status":"passed","time":{"start":1760648913857,"stop":1760648927300,"duration":13443}},{"uid":"bff77c04d84c5463","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x55aec38d167a <unknown>\n#1 0x55aec3350566 <unknown>\n#2 0x55aec338bb4c <unknown>\n#3 0x55aec33877c4 <unknown>\n#4 0x55aec33d6bd3 <unknown>\n#5 0x55aec33d6286 <unknown>\n#6 0x55aec33c8403 <unknown>\n#7 0x55aec3394b02 <unknown>\n#8 0x55aec33957c1 <unknown>\n#9 0x55aec3895448 <unknown>\n#10 0x55aec38992af <unknown>\n#11 0x55aec387c8d9 <unknown>\n#12 0x55aec3899e55 <unknown>\n#13 0x55aec386213f <unknown>\n#14 0x55aec38be4b8 <unknown>\n#15 0x55aec38be693 <unknown>\n#16 0x55aec38d0613 <unknown>\n#17 0x7f4e1ba5fb7b <unknown>","time":{"start":1760647338851,"stop":1760647338851,"duration":0}},{"uid":"b9e89542f209e206","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127","time":{"start":1760646032684,"stop":1760646032684,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["ui","smoke"]},"source":"4b932e63abf59bff.json","parameterValues":["{'email': 'test2@mail.ru', 'name': 'User25', 'password': 'qwertyu1'}"]}